variables:
  DOCKER_DRIVER: overlay2

services:
  - docker:stable-dind

stages:
  - build
  - test
  - release

build-docker:
  image: docker:stable
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - if [ ! -z $CI_COMMIT_TAG ]; then docker tag $CI_REGISTRY_IMAGE:latest $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG && docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG; fi
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - dev
    - stable

test:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  before_script:
    - pip install coverage
  script:
    - python manage.py test

pages:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  stage: release
  before_script:
    - pip install -r docs/requirements.txt
  script:
    - cd docs
    - make html
    - mv build/html ../public
  artifacts:
    paths:
      - public
  only:
    refs:
     - stable
     - dev
    changes:
     - docs/*
