# Generated by Django 3.1.2 on 2020-10-29 12:42

from django.db import migrations, models
import django.db.models.deletion
import vpn_manager.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_wireguard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowConfigLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=vpn_manager.models.gen_token, max_length=32, verbose_name='Token')),
                ('peer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='show_config_token', to='django_wireguard.wireguardpeer', verbose_name='WireGuard Peer')),
            ],
        ),
    ]
